### ISSUE TITLE
Remove FB, G+ logos from support feedback landing page

### ISSUE THREAD

**Issue by grethelgahler** [toggl/thumbler#17]
Maybe try TW green and Toggl red Twitter bird icons instead and remove the rest? If doesn't look good, don't add it at all and remove all logos from there.

![screen shot 2015-11-02 at 15 39 37](https://cloud.githubusercontent.com/assets/8087318/10883235/2f98f3f8-8179-11e5-9132-579f5143c62a.png)

**Comment by syko** [comment]
Did not look good. Removed all buttons.
