### ISSUE TITLE
Endpoint needed for a munin chart

### ISSUE THREAD

**Issue by kadrihvl** [toggl/thumbler#25]
Endpoint needed to get the information below.
Chart's description:
Thumbler desk statistics per day - yearly munin chart
Two lines - total positive clicks; total negative clicks from http://thumbler.toggl.com/thumbs/list
Note: follow only 'desk-toggl' data of support agents Tiina Käärik, Róbert Fonó, Vedran Fak, Michelle Renee Jackson, Nick Robertson, Nina Žderić.

**Comment by kadrihvl** [comment]
@syko - please let backend team know when they can expect this endpoint.

**Comment by tcrammond** [comment]
@refiito do you know what data format you'd want to receive from this endpoint?

**Comment by refiito** [comment]
let's keep it simple (hopefully), so, something in the lines of:
```json
[{
	"agent": "Kadri",
	"positive": 2,
	"negative": 2
}, {
	"agent": "Tiina",
	"positive": 2,
	"negative": 2
}]
```

maybe?

and also, given this is supposed to be "feedback per day" return always the data for "yesterday" (sufficient currently, no need to complicate stuff) as the fetch will be running at some point during the day (all dates/times in UTC, as usual)
