### ISSUE TITLE
Use Yarn

### ISSUE THREAD

**Issue by langri-sha** [toggl/thumbler#30]
@langri-sha commented on [Wed Mar 14 2018](https://github.com/toggl/webapp/issues/6801)

**Comment by shantanuraj** [comment]
https://github.com/toggl/thumbler/commit/4a7c43fcce0cc068222c5970ef8445c0bd10db00#diff-8ee2343978836a779dc9f8d6b794c3b2

This added a yarn.lock to the upgrade-all-libs branch so I think we can close this one.

**Comment by langri-sha** [comment]
Yup 👍! Need to add the error log to the ignore patterns 🏃 💨.
