### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by langri-sha** [toggl/thumbler#32]
@langri-sha commented on [Wed Mar 14 2018](https://github.com/toggl/webapp/issues/6803)

**Comment by shantanuraj** [comment]
Prettier doesn't support coffeescript yet so we are blocked #34

**Comment by langri-sha** [comment]
We [forced pragma checks](https://github.com/toggl/webapp/blob/5806/custom-currencies-scrollbar/toggl/prettier/index.js#L3) in `webapp`, but we don't need it now.

Let's assume everyone is using Prettier.
