### ISSUE TITLE
Use JavaScript

### ISSUE THREAD

**Issue by shantanuraj** [toggl/thumbler#34]
Tooling around JS is much better than CoffeeScript
The source is small enough that it won't take much time

**Comment by langri-sha** [comment]
We still have repos like https://github.com/toggl/thumbler-conf/blob/master around, so we'll need to keep the CS tranformation for until then.

**Comment by shantanuraj** [comment]
Okay.

**Comment by shantanuraj** [comment]
@langri-sha btw looking at thumber-conf
I am not sure if the change to js will affect it directly (?) assuming it depends on the package.json scripts and until we keep that protocol unchanged it should work

**Comment by langri-sha** [comment]
If we keep `coffee-script/register` in the `www` bin script and the `gulpfile` we should be ok for now 👍.
