### ISSUE TITLE
Generate separate "thumbler" for support articles with feedback form

### ISSUE THREAD

**Issue by grethelgahler** [toggl/thumbler#9]
Need to be discussed
Also, thumbler design is still in progress

**Comment by syko** [comment]
![support 1-1](https://cloud.githubusercontent.com/assets/317674/10216198/74907148-6851-11e5-95f8-5ee87a39675b.png)
![support 1-2](https://cloud.githubusercontent.com/assets/317674/10216199/74e8148e-6851-11e5-98d9-ed863179f6ad.png)
![support 1-3](https://cloud.githubusercontent.com/assets/317674/10216200/74fde80e-6851-11e5-8138-e3d1fa8e6984.png)

**Comment by syko** [comment]
Done, see http://github.com/toggl/thumbler-voter
